services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  System25\T3twigs\:
    resource: '../Classes/*'

  System25\T3twigs\Typo3\TwigContentObject:
    tags:
      - name: frontend.contentobject
        identifier: 'TWIGTEMPLATE'
